### PR TITLE
[MOD-2075] Multicast Support for iOS and Android

### PR DESCRIPTION
**Pull request by muhammaddadu**
[Jira Ticket](https://jira.appcelerator.org/browse/MOD-2075)
PR taken from https://github.com/appcelerator/titanium_modules/pull/130

### CODE REVIEW

**Comment by hansemannn** [comment]
Closing due to outdated source and missing backwards compatibility.

**Comment by focussing** [comment]
@hansemannn I used the Ti.UDP module a lot in projects. Now I need to do an urgent update to an existing Appcelerator Android app that worked fine in 2019 using Ti SDK 6.3.0. I have the iOS variant up and running using SDK 10.1.1, but I can't get the Android one to work...

I tried many things to get it compiled, but nothing helps:
```
[WARN] :   The module ti.udp does not support the ABI: arm64-v8a
[WARN] :   It only supports the following ABIs: armeabi-v7a, x86
[WARN] :   Your application will most likely encounter issues
```
Don't know what to do...

Could you please help me to make a new Ti.UDP module that can be used in newer Appcelerator apps, that use latest SDK's?
There are more people out there that use this module and are stuck...

The sources for the Ti.UDP module can be downloaded from  www.focussing.nl/ti.udp-master.zip

**Comment by hansemannn** [comment]
Hey there! You can reach me via TiSlack (`@hans`) and we can sort it timely.

**Comment by focussing** [comment]
Hey @hansemannn thank you for your reply. Michael Gangolf has helped me with a brandnew updated Ti.UDP module :)

**Pull request closed without merging**
